<?php
/**
 * Z-FINANCE 1.0.0 - Income Reports & Exports
 * modules/income/income_reports.php
 */
if (!defined('Z_FINANCE_INIT')) die('Direct access not permitted');
?>

<div class="row g-4">
    <div class="col-md-4">
        <div class="card border-0 shadow-sm">
            <div class="card-header bg-white py-3">
                <h6 class="m-0 fw-bold text-dark"><i class="bi bi-file-earmark-bar-graph me-2 text-primary"></i>Generate Report</h6>
            </div>
            <div class="card-body">
                <form id="reportGenForm">
                    <div class="mb-3">
                        <label class="form-label fw-bold">Report Type</label>
                        <select class="form-select">
                            <option>Daily Income Report</option>
                            <option>Weekly Income Report</option>
                            <option selected>Monthly Income Report</option>
                            <option>Yearly Income Report</option>
                            <option>Category Breakdown Report</option>
                            <option>Source Performance Report</option>
                            <option>Customer Revenue Report</option>
                            <option>Service Income Report</option>
                            <option>Project Revenue Report</option>
                        </select>
                    </div>
                    <div class="mb-3">
                        <label class="form-label fw-bold">Date Range</label>
                        <div class="input-group">
                            <input type="date" class="form-control" value="2026-07-01">
                            <span class="input-group-text">to</span>
                            <input type="date" class="form-control" value="2026-07-31">
                        </div>
                    </div>
                    <div class="mb-3">
                        <label class="form-label fw-bold">Export Format</label>
                        <div class="btn-group w-100" role="group">
                            <input type="radio" class="btn-check" name="exportFormat" id="pdfFmt" checked>
                            <label class="btn btn-outline-danger" for="pdfFmt"><i class="bi bi-file-pdf me-1"></i>PDF</label>
                            
                            <input type="radio" class="btn-check" name="exportFormat" id="xlsFmt">
                            <label class="btn btn-outline-success" for="xlsFmt"><i class="bi bi-file-excel me-1"></i>Excel</label>

                            <input type="radio" class="btn-check" name="exportFormat" id="csvFmt">
                            <label class="btn btn-outline-primary" for="csvFmt"><i class="bi bi-filetype-csv me-1"></i>CSV</label>
                        </div>
                    </div>
                    <button type="button" class="btn btn-primary w-100 fw-bold" onclick="alert('Exporting statement...')"><i class="bi bi-download me-1"></i>Download Statement</button>
                </form>
            </div>
        </div>
    </div>
    <div class="col-md-8">
        <div class="card border-0 shadow-sm">
            <div class="card-header bg-white py-3">
                <h6 class="m-0 fw-bold text-dark"><i class="bi bi-clock-history me-2 text-primary"></i>Saved / Recent Reports</h6>
            </div>
            <div class="table-responsive">
                <table class="table table-hover align-middle mb-0">
                    <thead class="table-light">
                        <tr>
                            <th>Report Name</th>
                            <th>Period</th>
                            <th>Generated By</th>
                            <th>Generated At</th>
                            <th class="text-end">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td class="fw-bold"><i class="bi bi-file-pdf text-danger me-2"></i>Q2-2026 Category Analysis</td>
                            <td>Apr 2026 - Jun 2026</td>
                            <td>Super Admin</td>
                            <td>2026-07-01 10:15</td>
                            <td class="text-end"><button class="btn btn-sm btn-light"><i class="bi bi-download"></i></button></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
